import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import FullScreenBg from "../ui/bgFullScreen";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Telegram",
  description: "Generated by create next app",
  openGraph: {
    title: 'Telegram web app',
    description: 'Telegram web app. 网页版Telegram APP，免VPN的',
    url: 'https://telegram.codelin.vip',
    siteName: '免VPN版Telegram web app',
    images: [{ url: 'https://telegram.codelin.vip/favicon.ico' }]
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-CN" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full bg-gray-900 text-white`}
      >
        {children}
        <FullScreenBg />

      </body>
    </html>
  );
}
